/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gear2.glb -T 
Files: gear2.glb [737.6KB] > /Users/zihongchen/HackG/FRC-Website/public/models/gear2-transformed.glb [27.42KB] (96%)
*/

import {React, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react';
import gsap from 'gsap/all';


export default function Gear2(props) {
  const gearRef = useRef(null);
  const { nodes, materials, scene } = useGLTF(import.meta.env.BASE_URL +'/models/gear2-transformed.glb')
  useGSAP(() => {
    if (gearRef.current) {
     
      gsap.to(gearRef.current.rotation, {
        y: Math.PI * 2, 
        duration: 10,
        ease: "none",
        repeat: -1 
      })
      gsap.from(gearRef.current.position, {
        z: -1, 
        duration: 4,
        ease: "back.out(.4)"
        
      })
    }
  }, [])
  return (
    <group {...props} dispose={null}>
      <mesh ref={gearRef} geometry={nodes.mesh0_mesh.geometry} >
        <meshStandardMaterial color="black" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/gear2-transformed.glb')
