/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gear1.glb -T 
Files: gear1.glb [382.24KB] > /Users/zihongchen/HackG/FRC-Website/public/models/gear1-transformed.glb [13.19KB] (97%)
*/

import {React, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap/all'
import {useGSAP} from "@gsap/react"



export default function Gear1(props) {
  const { nodes, materials, scene } = useGLTF(import.meta.env.BASE_URL + '/models/gear1-transformed.glb')
  const gearRef = useRef(null);
  useGSAP(() => {
    if (gearRef.current) {
     
      gsap.to(gearRef.current.rotation, {
        y: Math.PI * 2, 
        duration: 10,
        ease: "none",
        repeat: -1 
      })
      gsap.from(gearRef.current.position, {
        x: 1, 

        duration: 4,
        ease: "back.out(.4)"
        
      })
    }
  }, [])
  return (
    <group  {...props} dispose={null}>
      <mesh ref = {gearRef} geometry={nodes.mesh0_mesh.geometry} material={materials['0.215686_0.215686_0.215686_0.000000_0.000000']} />
    </group>
  )
}

useGLTF.preload('/models/gear1-transformed.glb')
